FORMAT: 1A
HOST: http://tmadashboard001.apiblueprint.org/

# Dashboard 001

Dashboard 001 is a simple test API that shows data from 
factory machines doing tests on the manufacturing line output. The API
conforms to [HATEOAS principles](https://en.wikipedia.org/wiki/HATEOAS) for browseable APIs. 

Refs.
- [online example](https://sendgrid.com/blog/quickly-prototype-apis-apiary/) 
- the Apiari tutorial

## Machines Collection [/machines]

Shows the list of machines with browseable API to discover the phase details

### List All Machines [GET]

+ Response 200 (application/json)

        [
            {
                "machine_id": "mch1234",
                "machine_name": "Machine 1234",
                "efficiency": [
                    {
                        "line_name": "L",
                        "details_url": "/phases/mch1234/L",
                        "value": 86
                    }
                    {
                        "line_name": "R",
                        "details_url": "/phases/mch1234/R",
                        "value": 92
                    }
                ]
            }
        ]

## Phases [/phases/{machine_id}/{line_id}]

can be used both for 

- cumulative gain/loss, by making a simple difference between `cycle_time_exp` and all the values detailed in `cycle_time_act` and
- cycle time series, by plotting each value in `cycle_time_act` with respective *EV*

+ Parameters
    + machine_id (string) - machine id
    + line_id (string) - line id

### Phases details by machine [GET]

+ Response 200 (application/json)

        {
            "machine_name": "",
            "phases": [
                {
                    "phase_name": "phase 1",
                    "phase_description": "phase 1 bla bla",
                    "cycle_time_act": [
                        {
                            "time": "2016-02-16T10:54:47.569Z"
                            "value": 110 
                        },
                        {
                            "time": "2016-02-16T10:55:47.569Z"
                            "value": 118 
                        },
                    ],
                    "cycle_time_exp": 120,
                },
                {
                    "phase_name": "phase 2",
                    "phase_description": "phase 2 bla bla",
                    "cycle_time_act": [
                        {
                            "time": "2016-02-16T10:54:47.569Z"
                            "value": 241 
                        },
                        {
                            "time": "2016-02-16T10:55:47.569Z"
                            "value": 245 
                        },
                    ],
                    "cycle_time_exp": 240,
                }
            ]
        }